apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: doc-ia-hpa
  namespace: doc-ia
  labels:
    app.kubernetes.io/name: doc-ia
    app.kubernetes.io/component: autoscaler
    app.kubernetes.io/part-of: doc-ia-system
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/version: "2.3.0"
  annotations:
    description: "Horizontal Pod Autoscaler for DocIA"
    autoscaling.alpha.kubernetes.io/metrics: "cpu,memory,custom"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: doc-ia-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
    # CPU utilization
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    # Memory utilization
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    # Custom metrics (if available)
    - type: Pods
      pods:
        metric:
          name: http_requests_per_second
        target:
          type: AverageValue
          averageValue: "100"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
        - type: Pods
          value: 1
          periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
        - type: Pods
          value: 2
          periodSeconds: 60
      selectPolicy: Max
