apiVersion: v1
kind: ServiceAccount
metadata:
  name: doc-ia-service-account
  namespace: doc-ia
  labels:
    app.kubernetes.io/name: doc-ia
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: doc-ia-system
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/version: "2.3.0"
  annotations:
    description: "Service account for DocIA application"
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: doc-ia-role
  namespace: doc-ia
  labels:
    app.kubernetes.io/name: doc-ia
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: doc-ia-system
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/version: "2.3.0"
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: doc-ia-role-binding
  namespace: doc-ia
  labels:
    app.kubernetes.io/name: doc-ia
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: doc-ia-system
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/version: "2.3.0"
subjects:
  - kind: ServiceAccount
    name: doc-ia-service-account
    namespace: doc-ia
roleRef:
  kind: Role
  name: doc-ia-role
  apiGroup: rbac.authorization.k8s.io
